### PR TITLE
Fsm to Circuit (Follow Spec.)

### PR DESCRIPTION
**Pull request by BookGin**
Now it's corresponded with the spec.

In addition, please ignore my testing commit:
`Testing on deleting surplus gates, but bugs left,  b714a16be`

### CODE REVIEW

**Comment by CTinRay** [comment]
Why don't you just put what in `fsm2schematic.js` in `forward.js`?

And for QM series file, I think you may consider either making a directory under `./js/` for it, or merge them in Algorithm “namespace", now that it is in `algorithm` directory. 
There may not be such convension, but maybe that will make our file structure more logical?

**Comment by BookGin** [comment]
Sure. I'll fix them ASAP.

**Comment by BookGin** [comment]
@CTinRay 
I merged `fsm2schematic.js` into `forward.js`

In addition, how about this file hierarchy?

```
├── algorithm
│   ├── forward.js
│   ├── qm
│   │   ├── QMAlgorithm.js
│   │   └── qm-min.js
│   ├── reverse.js
│   └── test-forward.html
├── gate.js
├── gui
│   ├── fsm.js
│   ├── init.js
│   ├── schematic.js
│   └── view.js
├── jointjs.shapes.fsm.js
└── jointjs.shapes.gate.js
```

**Comment by CTinRay** [comment]
It looks good.
But now that `QMAlgorithm` is not in `Algorithm` namespace, maybe it will be better to put the directory in `./js`?

And [here](https://github.com/DSDL2016/FwdRevDesign/blob/fsm2circuit/js/algorithm/forward.js#L7) 

``` js
var Fsm2schematic = Fsm2schematic || {};
```

A global variable is exposed.

One more thing is, for the function 

```
Fsm2schematic.convert = function(fsm, totalBit) {
```

is `totalBit` a necessary argument?
I mean, it can calculate `totalBit` without telling it bah?

**Comment by BookGin** [comment]
@CTinRay 

> But now that QMAlgorithm is not in Algorithm namespace, maybe it will be better to put the directory in ./js?

OK, I'll move `QMAlgorithm` under `Algorithm` namespace.

> `var Fsm2schematic = Fsm2schematic || {};`
> A global variable is exposed.

`Fsm2schematic` is considered as a OOP `class` here. If you really care about it, I'll put it under `Algorithm` namespace. 
One more thing is that in `qm-min.js`, there are many global variables as well....

> `totalBit` a necessary argument?

If the input `fsm` follows with my spec, it's unnecessary.

**Comment by y3nr1ng** [comment]
小問題.. 為什麼要 `var Fsm2schematic = Fsm2schematic || {};` 這樣寫啊 D: 網路上都沒翻到說明

**Comment by CTinRay** [comment]
@BookGin 
If you want, you can wrap qm-min.js in an anonymous function and only expose some function.

FSM will follow your spec, but index may be `1`, `2`, `3`, rather than `01`, `10`.

@liuyenting 
To prevent overwriting existing `Fsm2schematic`.

**Comment by BookGin** [comment]
@CTinRay 
Can I put `QMAlgorithm` under `Algorithm` namespace without merging them into a single file?
Sorry I'm new to javascript......

**Comment by CTinRay** [comment]
@BookGin 
Yes, simply declare 

``` js
Algorithm = Algorithm || {};
```

as other files do at the begin of your code.

**Comment by BookGin** [comment]
@CTinRay 
Another question: 
In the namespace, can I get rid of typing something like `Algoeithm.Fsm2schematic.QMAlgorithm.simplify()`?
I think I'm writing _javascript_ , not _java_!

**Comment by CTinRay** [comment]
hmm...

``` js
let QMAlgorithm = Algoeithm.Fsm2schematic.QMAlgorithm;
```

in your scope may be a solution.

**Comment by BookGin** [comment]
Thank you for your quick response.
I'll refine the code with that tips in my next pull request.

**Pull request closed without merging**
